matrix:
  include:
    - stage: "java"
      language: java
      before_script: cd map_generator
      script: ant build

    - stage: "js"
      language: node_js
      before_script:
       - cd game
       - npm install --save-dev jshint
      node_js:
        - "node"

notifications:
  email:
    - n.sharif@windowslive.com