matrix:
  include:
    - stage: "java"
      install: true
      language: java
      before_script: cd map_generator
      script: ant build
      before_deploy:
        - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}  
        - git tag $TRAVIS_TAG
      deploy:
        - provider: pages
          skip_cleanup: true # Don't re-run the tests
          github_token: $GITHUB_TOKEN
          keep_history: true
          local_dir: build
          on:
            tags: true
            branch: master

    - stage: "js"
      language: node_js
      before_script:
       - cd game
       - npm install --save-dev jshint
      node_js:
        - "node"
      after_success: echo "jshint - no errors found"
      

notifications:
  email:
    - n.sharif@windowslive.com