matrix:
  include:
    language: java
    before_script: cd map_generator
    script: ant build
    after_script: cd..

    language: node_js
    node_js:
      - "node"
    before_script: cd game
    after_script: cd ..

notifications:
  email:
    - n.sharif@windowslive.com