matrix:
  include:
    - language: java
    before_script: cd map_generator
    script: ant warcraft2_map_generator
    after_script: cd..

    - language: javascript
    before_script: cd map_generator
    after_script: cd ..

notifications:
  email:
    - n.sharif@windowslive.com